CREATE TABLE COLL(ROLL INT PRIMARY KEY,NAME VARCHAR(50),
MARKS INT NOT NULL);
INSERT INTO COLL(ROLL,NAME,MARKS)VALUES
(101,"ANIL",78),(102,"BHUMIKA",93),
(103,"CHETAN",85),(104,"DHRUV",96),
(105,"EMANUEL",12),(106,"FARAH",82);
UPDATE COLL SET MARKS=92 WHERE ROLL=105;
SELECT AVG(MARKS) FROM COLL;
SELECT NAME,MARKS
FROM COLL WHERE MARKS>(SELECT AVG(MARKS) FROM COLL);
INSERT INTO COLL(ROLL,NAME,MARKS)VALUES
(107,"ARUSHI",99);


SELECT NAME,ROLL FROM COLL WHERE ROLL%2=0;
SELECT NAME,ROLL FROM COLL WHERE 
ROLL IN (SELECT ROLL FROM COLL WHERE ROLL%2=0);

ALTER TABLE COLL ADD COLUMN CITY VARCHAR(20);
UPDATE COLL SET CITY='PUNE' WHERE ROLL=101;
UPDATE COLL SET CITY='MUMBAI' WHERE ROLL=103;
UPDATE COLL SET CITY='DELHI' WHERE ROLL=106;

SELECT MAX(MARKS) FROM COLL WHERE CITY='DELHI';
SELECT MAX(MARKS) FROM (SELECT * FROM COLL WHERE CITY='DELHI') AS TEMP;

CREATE VIEW VIEW1 AS
SELECT ROLL,NAME AS NAMES FROM COLL;
SELECT * FROM VIEW1;
DROP VIEW VIEW1;