CREATE TABLE TEACHER(ID INT PRIMARY KEY);
INSERT INTO TEACHER VALUES(101),(102),(103);
SELECT * FROM TEACHER;
CREATE TABLE STUDENT(NAME VARCHAR(40), TEACHERID INT,
FOREIGN KEY(TEACHERID) REFERENCES TEACHER(ID));
SELECT * FROM STUDENT;
INSERT INTO STUDENT(NAME,TEACHERID) VALUES("RIYA",101),
("TINA",102),("SHREYA",103);
INSERT INTO STUDENT(NAME,TEACHERID) VALUES("NEHA",105);

CREATE TABLE EMP(ID INT, SALARY INT DEFAULT 25000);
INSERT INTO EMP(ID) VALUES(101);
INSERT INTO EMP(ID,SALARY) VALUES(101,30000);
SELECT * FROM EMP;

CREATE TABLE CITY(ID INT PRIMARY KEY, CITY VARCHAR(20),AGE INT,
CONSTRAINT CHECK (AGE>=18 AND CITY="DELHI"));
INSERT INTO CITY(ID,CITY,AGE) VALUES(1,"DELHI",26);
INSERT INTO CITY(ID,CITY,AGE) VALUES(1,"DELHI",6);
USE XYZ;
DROP TABLE CITY;