CREATE DATABASE CUSTOMER;
USE CUSTOMER;
CREATE TABLE CUSTOMER(ID INT PRIMARY KEY,CUSTOMER VARCHAR(50),
MODE VARCHAR(50), CITY VARCHAR(20));
INSERT INTO CUSTOMER(ID,CUSTOMER,MODE,CITY) VALUES
(101,"OLIVIA","NETBANKING","PORTLAND"),
(102,"ETHAN","CREDIT CARD","MIAMI"),
(103,"MAYA","CREDIT CARD","SEATTLE"),
(104,"LIAM","NETBANKING","DENVER"),
(105,"SOPHIA","CREDIT CARD","NEW YORK"),
(106,"CALEB","DEBIT CARD","MINNEAPOLIS"),
(107,"AVA","DEBIT CARD","PHOENIX"),
(108,"LUCAS","NETBANKING","BOSTON"),
(109,"ISABELLA","NETBANKING","NASHVILLE"),
(110,"JACKSON","CREDIT CARD","BOSTON");
SELECT MODE,COUNT(CUSTOMER) FROM CUSTOMER GROUP BY MODE;