CREATE DATABASE JOINS;
USE JOINS;

CREATE TABLE STUDENT(ID INT,NAME VARCHAR(10));
INSERT INTO STUDENT(ID,NAME) VALUES
(101,"ADAM"),(102,"BOB"),(103,"CASEY");

CREATE TABLE COURSE(ID INT,COURSE VARCHAR(20));
INSERT INTO COURSE(ID,COURSE) VALUES
(102,"ENG"),(105,"MATHS"),(103,"SCIENCE"),(107,"CS");

SELECT * FROM STUDENT INNER JOIN COURSE ON STUDENT.ID=COURSE.ID;
SELECT * FROM STUDENT AS S LEFT JOIN COURSE AS C ON S.ID=C.ID;
SELECT * FROM STUDENT AS S RIGHT JOIN COURSE AS C ON S.ID=C.ID;
SELECT * FROM STUDENT LEFT JOIN COURSE ON STUDENT.ID=COURSE.ID
UNION
SELECT * FROM STUDENT RIGHT JOIN COURSE ON STUDENT.ID=COURSE.ID;

SELECT * FROM STUDENT LEFT JOIN COURSE ON STUDENT.ID=COURSE.ID 
WHERE COURSE.ID IS NULL;

SELECT * FROM STUDENT RIGHT JOIN COURSE ON STUDENT.ID=COURSE.ID 
WHERE STUDENT.ID IS NULL;

CREATE TABLE EMPLOYEE(ID INT PRIMARY KEY, NAME VARCHAR(10),
MANAGER_ID INT);
INSERT INTO EMPLOYEE(ID,NAME,MANAGER_ID)VALUES(101,"ADAM",103),
(102,"BOB",104),(103,"CASEY",NULL),(104,"DONALD",103);
SELECT B.NAME,A.NAME AS MAGAER_NAME FROM EMPLOYEE AS A
JOIN EMPLOYEE AS B ON B.MANAGER_ID=A.ID;

SELECT ID,COURSE FROM COURSE UNION SELECT ID,NAME FROM STUDENT;
SELECT ID,NAME FROM EMPLOYEE UNION ALL SELECT ID,NAME FROM STUDENT;