CREATE DATABASE COLLEGE;
USE COLLEGE;
CREATE TABLE STUDENT(ROLL INT PRIMARY KEY,NAME VARCHAR(50),
MARKS INT NOT NULL, GRADE VARCHAR(1),CITY VARCHAR(20));
INSERT INTO STUDENT(ROLL,NAME,MARKS,GRADE,CITY) VALUES
(101,"ANIL",78,"C","PUNE"),(102,"BHUMIKA",93,"A","MUMBAI"),
(103,"CHETAN",85,"B","MUMBAI"),(104,"DHRUV",96,"A","DELHI"),
(105,"EMANUEL",12,"F","DELHI"),(106,"FARAH",82,"B","DELHI");
SELECT ROLL,MARKS FROM STUDENT;
SELECT * FROM STUDENT WHERE MARKS+10>90;
SELECT * FROM STUDENT WHERE ROLL%3=1;
SELECT * FROM STUDENT WHERE MARKS>80 AND GRADE="B";
SELECT * FROM STUDENT WHERE MARKS>80 OR GRADE="C";
SELECT * FROM STUDENT WHERE ROLL BETWEEN 103 AND 105;
SELECT * FROM STUDENT WHERE CITY IN ("DELHI","PUNE");
SELECT * FROM STUDENT WHERE GRADE NOT IN ("A");
SELECT * FROM STUDENT WHERE MARKS<93 LIMIT 3;
SELECT * FROM STUDENT ORDER BY CITY ASC;
SELECT * FROM STUDENT ORDER BY MARKS DESC LIMIT 3;

SELECT MAX(MARKS) FROM STUDENT;
SELECT COUNT(NAME) FROM STUDENT;
SELECT AVG(MARKS) FROM STUDENT WHERE CITY IN("MUMBAI");
SELECT CITY FROM STUDENT GROUP BY CITY HAVING AVG(MARKS)>40;

SELECT CITY,GRADE, COUNT(ROLL) FROM STUDENT GROUP BY CITY,GRADE;
SELECT CITY,AVG(MARKS) FROM STUDENT GROUP BY CITY ORDER BY CITY ASC;

USE COLLEGE;
SELECT CITY,COUNT(NAME) FROM STUDENT GROUP BY CITY HAVING MAX(MARKS)>95;

SET SQL_SAFE_UPDATES=0;
UPDATE STUDENT SET GRADE="O" WHERE GRADE="A";
UPDATE STUDENT SET GRADE="E" WHERE MARKS BETWEEN 80 AND 90;
UPDATE STUDENT SET MARKS=MARKS+5;
SELECT * FROM STUDENT;

DELETE FROM STUDENT WHERE MARKS>99;

ALTER TABLE STUDENT ADD COLUMN AGE INT NOT NULL DEFAULT 18;
ALTER TABLE STUDENT MODIFY COLUMN AGE VARCHAR(2);
INSERT INTO STUDENT(ROLL,NAME,MARKS,GRADE,CITY,AGE)VALUES(110,"ANUSHKA",73,"C","PUNE",20);
INSERT INTO STUDENT(ROLL,NAME,MARKS,GRADE,CITY,AGE)VALUES(111,"ATUL",98,"O","KOL","BA");
UPDATE STUDENT SET AGE=18 WHERE ROLL=111;
SELECT * FROM STUDENT_DET;
ALTER TABLE STUDENT CHANGE COLUMN AGE STU_AGE INT;
ALTER TABLE STUDENT DROP COLUMN STU_AGE;
ALTER TABLE STUDENT RENAME COLUMN CITY TO TOWN;
ALTER TABLE STUDENT RENAME TO STUDENT_DET;

TRUNCATE TABLE STUDENT_DET;
INSERT INTO STUDENT_DET(ROLL,NAME,MARKS,GRADE,TOWN) VALUES
(101,"ANIL",78,"C","PUNE"),
(103,"CHETAN",85,"B","MUMBAI"),(104,"DHRUV",96,"A","DELHI");

ALTER TABLE STUDENT_DET RENAME COLUMN NAME TO FULL_NAME;
ALTER TABLE STUDENT_DET CHANGE FULL_NAME FULL_NAME VARCHAR(100);
ALTER TABLE STUDENT_DET MODIFY FULL_NAME VARCHAR(10);

SET SQL_SAFE_UPDATES=0;
DELETE FROM STUDENT_DET WHERE MARKS<80;
ALTER TABLE STUDENT_DET DROP COLUMN GRADE;