USE COLLEGE;
CREATE TABLE DEPT( ID INT PRIMARY KEY, NAME VARCHAR(50));
CREATE TABLE TEACHER( ID INT PRIMARY KEY, NAME VARCHAR(50),DEPTID INT,
FOREIGN KEY (DEPTID) REFERENCES DEPT(ID));
DROP TABLE TEACHER;

CREATE TABLE TEACHER( ID INT PRIMARY KEY, NAME VARCHAR(50),DEPTID INT,
FOREIGN KEY (DEPTID) REFERENCES DEPT(ID)
ON UPDATE CASCADE
ON DELETE CASCADE
);

INSERT INTO DEPT(ID,NAME) VALUES(101,"AIML"),(102,"IOT");
UPDATE DEPT SET ID=103 WHERE ID=102;
SELECT * FROM DEPT;
INSERT INTO TEACHER(ID,NAME,DEPTID) VALUES
(80,"RAJ",102),(9,"ANU",101);
SELECT * FROM TEACHER;