CREATE DATABASE temp1; 
CREATE DATABASE COLLEGE;
DROP DATABASE COLLEGE;
DROP DATABASE temp1;
USE COLLEGE;
CREATE TABLE STUDENT (ID INT PRIMARY KEY, NAME VARCHAR(50));
INSERT INTO STUDENT(ID,NAME)VALUES(9,"ANU");
INSERT INTO STUDENT(ID,NAME)VALUES(80,"RAJ");
SELECT * FROM STUDENT;

CREATE DATABASE XYZ;
USE XYZ;
CREATE TABLE EMPLOYEE (ID INT PRIMARY KEY, NAME VARCHAR(100), SALARY INT);
INSERT INTO EMPLOYEE (ID,NAME,SALARY)VALUES(1,"Adam",25000),
(2,"Bob",30000),(3,"Casey",40000);
SELECT * FROM EMPLOYEE;

CREATE TABLE TEMP1(ID INT UNIQUE);
INSERT INTO TEMP1 VALUES (101);
INSERT INTO TEMP1 VALUES (101);
 
USE XYZ;
DROP TABLE TEMP1;

